/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiWaitlistVerifyRouteImport } from './routes/api/waitlist.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistVerifyRoute = ApiWaitlistVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiWaitlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/waitlist' | '/api/waitlist' | '/api/waitlist/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/waitlist' | '/api/waitlist' | '/api/waitlist/verify'
  id: '__root__' | '/' | '/waitlist' | '/api/waitlist' | '/api/waitlist/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiWaitlistRoute: typeof ApiWaitlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist/verify': {
      id: '/api/waitlist/verify'
      path: '/verify'
      fullPath: '/api/waitlist/verify'
      preLoaderRoute: typeof ApiWaitlistVerifyRouteImport
      parentRoute: typeof ApiWaitlistRoute
    }
  }
}

interface ApiWaitlistRouteChildren {
  ApiWaitlistVerifyRoute: typeof ApiWaitlistVerifyRoute
}

const ApiWaitlistRouteChildren: ApiWaitlistRouteChildren = {
  ApiWaitlistVerifyRoute: ApiWaitlistVerifyRoute,
}

const ApiWaitlistRouteWithChildren = ApiWaitlistRoute._addFileChildren(
  ApiWaitlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaitlistRoute: WaitlistRoute,
  ApiWaitlistRoute: ApiWaitlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
