/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Special150RouteImport } from './routes/special-150'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ApiSpecial150RouteImport } from './routes/api/special150'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiWaitlistVerifyRouteImport } from './routes/api/waitlist.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Special150Route = Special150RouteImport.update({
  id: '/special-150',
  path: '/special-150',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecial150Route = ApiSpecial150RouteImport.update({
  id: '/api/special150',
  path: '/api/special150',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistVerifyRoute = ApiWaitlistVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiWaitlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/special-150': typeof Special150Route
  '/waitlist': typeof WaitlistRoute
  '/api/special150': typeof ApiSpecial150Route
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/special-150': typeof Special150Route
  '/waitlist': typeof WaitlistRoute
  '/api/special150': typeof ApiSpecial150Route
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/special-150': typeof Special150Route
  '/waitlist': typeof WaitlistRoute
  '/api/special150': typeof ApiSpecial150Route
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/verify': typeof ApiWaitlistVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/special-150'
    | '/waitlist'
    | '/api/special150'
    | '/api/waitlist'
    | '/api/waitlist/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/special-150'
    | '/waitlist'
    | '/api/special150'
    | '/api/waitlist'
    | '/api/waitlist/verify'
  id:
    | '__root__'
    | '/'
    | '/special-150'
    | '/waitlist'
    | '/api/special150'
    | '/api/waitlist'
    | '/api/waitlist/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Special150Route: typeof Special150Route
  WaitlistRoute: typeof WaitlistRoute
  ApiSpecial150Route: typeof ApiSpecial150Route
  ApiWaitlistRoute: typeof ApiWaitlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-150': {
      id: '/special-150'
      path: '/special-150'
      fullPath: '/special-150'
      preLoaderRoute: typeof Special150RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/special150': {
      id: '/api/special150'
      path: '/api/special150'
      fullPath: '/api/special150'
      preLoaderRoute: typeof ApiSpecial150RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist/verify': {
      id: '/api/waitlist/verify'
      path: '/verify'
      fullPath: '/api/waitlist/verify'
      preLoaderRoute: typeof ApiWaitlistVerifyRouteImport
      parentRoute: typeof ApiWaitlistRoute
    }
  }
}

interface ApiWaitlistRouteChildren {
  ApiWaitlistVerifyRoute: typeof ApiWaitlistVerifyRoute
}

const ApiWaitlistRouteChildren: ApiWaitlistRouteChildren = {
  ApiWaitlistVerifyRoute: ApiWaitlistVerifyRoute,
}

const ApiWaitlistRouteWithChildren = ApiWaitlistRoute._addFileChildren(
  ApiWaitlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Special150Route: Special150Route,
  WaitlistRoute: WaitlistRoute,
  ApiSpecial150Route: ApiSpecial150Route,
  ApiWaitlistRoute: ApiWaitlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
